[project]
name = "detect-daoche"
version = "0.0.1"
requires-python = ">=3.14"
dependencies = [
  "mypy",
  "pyright",
  "ruff",
  "ultralytics>=8.4.78",
]

[tool.ruff]
line-length = 1000

[tool.ruff.lint]
select = [
  "E",    # pycodestyle (error)
  "F",    # pyflakes
  "B",    # bugbear
  "B9",
  "C4",   # flake8-comprehensions
  "SIM",  # flake8-simplify
  "I",    # isort
  "UP",   # pyupgrade
  "PIE",  # flake8-pie
  "PGH",  # pygrep-hooks
  "PYI",  # flake8-pyi
  "RUF",
  "S602", # flake8-bandit: subprocess-popen-with-shell-equals-true
]
ignore = ["B008", "B011", "E501", "RUF001"]

[tool.ruff.lint.isort]
combine-as-imports = true
